// AUTO-GENERATED by scripts/build-category-galleries.mjs from the re-scraped,
// page-associated asset manifest (public/assets/khs/asset-map.json). These are
// real Krishna Home Studio photographs, not stock imagery or invented products.
// Do not hand-edit; re-run the script to refresh after a fresh asset scrape.

export interface GalleryImage {
  src: string;
  alt: string;
}

export const categoryGalleries: Record<string, GalleryImage[]> = {
  "bath-accessories": [
    {
      "src": "/assets/khs/bathware/bath-accessories/WhatsApp-Image-2023-05-20-at-16.10.50.jpg",
      "alt": "WhatsApp Image 2023-05-20 at 16.10.50"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/Double-soap-R.G.png",
      "alt": "Double soap R.G"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/IMG-20231117-WA0017.jpg",
      "alt": "IMG-20231117-WA0017"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/IMG-20231117-WA0018.jpg",
      "alt": "IMG-20231117-WA0018"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/IMG-20231117-WA0020.jpg",
      "alt": "IMG-20231117-WA0020"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/IMG-20231117-WA0023.jpg",
      "alt": "IMG-20231117-WA0023"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/IMG-20231117-WA0025.jpg",
      "alt": "IMG-20231117-WA0025"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/IMG-20231117-WA0026.jpg",
      "alt": "IMG-20231117-WA0026"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/IMG-20231117-WA0028.jpg",
      "alt": "IMG-20231117-WA0028"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/IMG-20231117-WA0045.jpg",
      "alt": "IMG-20231117-WA0045"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/IMG-20231117-WA0047.jpg",
      "alt": "IMG-20231117-WA0047"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/IMG-20231117-WA0048.jpg",
      "alt": "IMG-20231117-WA0048"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/IMG-20231117-WA0049.jpg",
      "alt": "IMG-20231117-WA0049"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/IMG-20231117-WA0050.jpg",
      "alt": "IMG-20231117-WA0050"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/IMG-20231117-WA0055.jpg",
      "alt": "IMG-20231117-WA0055"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/Untitled-design-10.png",
      "alt": "Untitled design (10)"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/Untitled-design-12.png",
      "alt": "Bathroom Accessories"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/Untitled-design-11.png",
      "alt": "Untitled design (11)"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/Untitled-design-14.png",
      "alt": "Untitled design (14)"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/Untitled-design-13.png",
      "alt": "Untitled design (13)"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/Untitled-design-12-1.png",
      "alt": "Untitled design (12)"
    },
    {
      "src": "/assets/khs/bathware/bath-accessories/Untitled-design-11-1.png",
      "alt": "Untitled design (11)"
    }
  ],
  "countertop-basin": [
    {
      "src": "/assets/khs/bathware/countertop-basin/IMG-20230520-WA0072.jpg",
      "alt": "IMG-20230520-WA0072"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/IMG-20230520-WA0029.jpg",
      "alt": "IMG-20230520-WA0029"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/IMG-20230520-WA0049.jpg",
      "alt": "IMG-20230520-WA0049"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/IMG-20230520-WA0052.jpg",
      "alt": "IMG-20230520-WA0052"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/IMG-20230520-WA0057.jpg",
      "alt": "IMG-20230520-WA0057"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/IMG-20230520-WA0069.jpg",
      "alt": "IMG-20230520-WA0069"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/IMG-20230520-WA0096.jpg",
      "alt": "IMG-20230520-WA0096"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/IMG-20230520-WA0113.jpg",
      "alt": "IMG-20230520-WA0113"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/IMG-20230520-WA0115.jpg",
      "alt": "IMG-20230520-WA0115"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/IMG-20230808-WA0021.jpg",
      "alt": "IMG-20230808-WA0021"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/IMG-20230808-WA0033.jpg",
      "alt": "IMG-20230808-WA0033"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/IMG-20230808-WA0046.jpg",
      "alt": "IMG-20230808-WA0046"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/IMG-20230808-WA0048.jpg",
      "alt": "IMG-20230808-WA0048"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/IMG-20240129-WA0004.jpg",
      "alt": "IMG-20240129-WA0004"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/IMG-20240129-WA0008.jpg",
      "alt": "IMG-20240129-WA0008"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/IMG-20240221-WA0061.jpg",
      "alt": "IMG-20240221-WA0061"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/WhatsApp-Image-2023-07-26-at-11.58.54.jpg",
      "alt": "WhatsApp Image 2023-07-26 at 11.58.54"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/WhatsApp-Image-2023-07-26-at-11.59.02.jpg",
      "alt": "WhatsApp Image 2023-07-26 at 11.59.02"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/IMG-20230520-WA0006.jpg",
      "alt": "IMG-20230520-WA0006"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/IMG-20230520-WA0008.jpg",
      "alt": "IMG-20230520-WA0008"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/IMG-20230520-WA0018.jpg",
      "alt": "IMG-20230520-WA0018"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/IMG-20230520-WA0028.jpg",
      "alt": "IMG-20230520-WA0028"
    },
    {
      "src": "/assets/khs/bathware/countertop-basin/bathroom-4032529_1280.jpg",
      "alt": "bathroom-4032529_1280"
    }
  ],
  "kitchen-sinks-faucets": [
    {
      "src": "/assets/khs/bathware/kitchen-sinks-faucets/modular-kitchen-design.jpg",
      "alt": "Modular kitchen design for your home - Beautiful Homes"
    }
  ],
  "shower-faucets": [
    {
      "src": "/assets/khs/bathware/shower-faucets/22541IN-4FP-CP600X600_2_800x.webp",
      "alt": "22541IN-4FP-CP600X600_2_800x"
    },
    {
      "src": "/assets/khs/bathware/shower-faucets/pexels-vika-glitter-3315291-scaled.jpg",
      "alt": "pexels-vika-glitter-3315291"
    },
    {
      "src": "/assets/khs/bathware/shower-faucets/Untitled-design-6.png",
      "alt": "Untitled design (6)"
    }
  ],
  "standalone-basin": [
    {
      "src": "/assets/khs/bathware/standalone-basin/IMG-20230520-WA0005.jpg",
      "alt": "IMG-20230520-WA0005"
    },
    {
      "src": "/assets/khs/bathware/standalone-basin/IMG-20230520-WA0091.jpg",
      "alt": "IMG-20230520-WA0091"
    },
    {
      "src": "/assets/khs/bathware/standalone-basin/IMG-20230520-WA0094.jpg",
      "alt": "IMG-20230520-WA0094"
    },
    {
      "src": "/assets/khs/bathware/standalone-basin/IMG-20230520-WA0125.jpg",
      "alt": "IMG-20230520-WA0125"
    },
    {
      "src": "/assets/khs/bathware/standalone-basin/IMG-20230520-WA0126.jpg",
      "alt": "IMG-20230520-WA0126"
    }
  ],
  "vanity-mirrors": [
    {
      "src": "/assets/khs/bathware/vanity-mirrors/pexels-max-vakhtbovycn-6186825-scaled.jpg",
      "alt": "pexels-max-vakhtbovycn-6186825"
    }
  ],
  "water-softeners-heaters": [
    {
      "src": "/assets/khs/bathware/water-softeners-heaters/images-1.jpg",
      "alt": "images (1)"
    }
  ],
  "shower-enclosures": [],
  "spa-wellness": [],
  "washbasins-waterclosets-urinals": [],
  "hardware": [
    {
      "src": "/assets/khs/hardware/Krishna-Home-Studio-Hardware-2.png",
      "alt": "Krishna Home Studio -Hardware (2)"
    },
    {
      "src": "/assets/khs/hardware/Krishna-Home-Studio-Hardware-3.png",
      "alt": "Krishna Home Studio -Hardware (3)"
    },
    {
      "src": "/assets/khs/hardware/Untitled-design-23.png",
      "alt": "Untitled design (23)"
    },
    {
      "src": "/assets/khs/hardware/WhatsApp-Image-2023-02-21-at-12.31.34.webp",
      "alt": "WhatsApp-Image-2023-02-21-at-12.31.34"
    },
    {
      "src": "/assets/khs/hardware/71-SG2KVhL._AC_UF10001000_QL80_.jpg",
      "alt": "71-SG2KVh+L._AC_UF1000,1000_QL80_"
    }
  ]
};
